FROM docker.io/library/python:3.12-slim
WORKDIR /mnt/locust
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY locustfile.py .
EXPOSE 8089 5557
ENTRYPOINT ["locust"]
